[32mINFO    [0m AF8YVB1805003480:log_util.py:49 AF8YVB1805003480, screen_on(), None
[1m[31mERROR   [0m AF8YVB1805003480:log_util.py:55 Fail to execute AF8YVB1805003480, click(x=100): 
Traceback (most recent call last):
  File "D:\PyCharmProjects\putest\core\uiautomator.py", line 93, in wrapper
    func_return = func(self, *args, **kwargs)
TypeError: click() missing 1 required positional argument: 'y'

[32mINFO    [0m AF8YVB1805003480:log_util.py:49 AF8YVB1805003480, screenshot(filename=D:\PyCharmProjects\putest\core\../result/1/screenshot\AF8YVB1805003480_click_2025_09_04_14_24_02.png), D:\PyCharmProjects\putest\core\../result/1/screenshot\AF8YVB1805003480_click_2025_09_04_14_24_02.png
[1m[31mERROR   [0m AF8YVB1805003480:log_util.py:55 The path of fail time screenshot is D:\PyCharmProjects\putest\core\../result/1/screenshot\AF8YVB1805003480_click_2025_09_04_14_24_02.png
[32mINFO    [0m AF8YVB1805003480:log_util.py:49 AF8YVB1805003480, press(key=home), True